#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=95

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1
CONFIG=/etc/shadowsocks.json

start() {
  # Proxy Mode
  service_start /data/usr/sbin/ss-redir -c $CONFIG -b 0.0.0.0
}

stop() {
  # Proxy Mode
  service_stop /data/usr/sbin/ss-redir
}
