#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=95

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1
CONFIG_FILE=/etc/shadowsocks.json


start() {
    service_start /data/usr/sbin/ss-redir -c $CONFIG_FILE -b 0.0.0.0
}

stop() {
    service_stop /data/usr/sbin/ss-redir
}
